# 01 How an Array Is Different from a List

| | |
|---|---|
| **Path** | NumPy |
| **Prerequisite** | Python Fundamentals, especially lists |

A Python list can hold anything, and each item lives on its own. A NumPy array holds values of one type in a rectangular block. That single restriction is why the later lessons can add a million numbers without writing a million additions.

Every example in this path has the same rhythm.

1. **Predict** the values and the shape before you read the output.
2. **Run.** The cell has already been executed. The stored output is the answer key.
3. When a formula is involved, the prediction is the hand calculation. NumPy then recomputes it.
4. **One pitfall** shows a case that looks almost right.
5. A **summary** keeps the rule.

`shape` is the size along each axis. A list of three numbers has shape `(3,)`. The comma matters: `(3,)` is a one-axis array, and `(3)` is only the number 3.


## Example 1 — A list becomes an array

### Predict

Three integers stay integers. The array has one axis of length 3, so the shape is `(3,)` and the number of elements is 3.

### Run


In [1]:
import numpy as np

# array copies the list into one block of numbers.
values = np.array([10, 20, 30])
print(values)
print(values.shape)
print(values.size)


[10 20 30]
(3,)
3


## Example 2 — Filled arrays, without writing every entry

### Predict

`zeros(3)` is three zeros. `ones((2, 3))` is two rows and three columns of ones: six values. `full` fills every entry with the same number. `eye(3)` puts ones on the diagonal of a $3\times 3$ identity and zeros elsewhere.

$$
I_3 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

### Run


In [2]:
import numpy as np

print(np.zeros(3))
# The pair (2, 3) is the shape: 2 rows, 3 columns.
print(np.ones((2, 3)))
print(np.full((2, 2), 7))
print(np.eye(3))


[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Example 3 — Counting and even spacing

### Predict

`arange(5)` starts at 0 and stops before 5, just as `range(5)` does: $0,1,2,3,4$.

`linspace(0, 1, 5)` includes both ends and places five values with equal gaps of $1/4$:

$$
0,\ \dfrac{1}{4},\ \dfrac{1}{2},\ \dfrac{3}{4},\ 1.
$$

### Run


In [3]:
import numpy as np

# Stop is excluded, the same rule as range.
print(np.arange(5))
# 5 points from 0 to 1, and both ends are included.
print(np.linspace(0, 1, 5))


[0 1 2 3 4]
[0.   0.25 0.5  0.75 1.  ]


## Example 4 — One float changes the whole array

### Predict

An array has one dtype. Writing `1.5` among integers promotes every entry to floating point. The shape is still `(3,)`.

### Run


In [4]:
# Example 4 — One float changes the whole array.
import numpy as np

whole = np.array([1, 2, 3])
mixed = np.array([1, 2, 1.5])
print(whole.dtype)
print(mixed.dtype)
print(mixed)


int64
float64
[1.  2.  1.5]


## A pitfall

`arange` with a fractional step counts until it passes the stop, and binary fractions are not exact. `arange(0, 1, 0.1)` does not reliably mean "eleven tenths." When you want a known number of points between two ends, use `linspace`.

A second trap: a ragged list is not a rectangle. NumPy refuses to guess.

### Run


In [5]:
import numpy as np

# A fractional step is a poor way to ask for tenths.
steps = np.arange(0, 1, 0.1)
print(steps.size)
# linspace is the tool that includes both ends and counts the points.
print(np.linspace(0, 1, 11).size)
try:
    print(np.array([[1, 2], [3, 4, 5]]))
except ValueError as error:
    print(type(error).__name__)


10
11
ValueError


## Summary

Build an array with `np.array`, or fill one with `zeros`, `ones`, `full`, `eye`, `arange`, and `linspace`. Every entry has the same dtype, and the shape is a tuple whose entries multiply to `size`. Use `linspace` when both ends and the count matter. A row that is longer than the others is not an array.
