# 02 Shape, dtype, and reshape

| | |
|---|---|
| **Path** | NumPy |
| **Prerequisite** | 01 |

`ndim` is the number of axes. `shape` is the length of each axis. `size` is the product of those lengths.

$$
\mathrm{size} = n_0 \cdot n_1 \cdots n_{d-1}.
$$

`reshape` rewraps the same elements into a new shape. The product of the new lengths must equal `size`. A length of `-1` means "whatever is left."


## Example 1 — Read the three facts

### Predict

Twelve numbers in a row have `ndim` 1, `shape` `(12,)`, and `size` 12.

### Run


In [1]:
# Example 1 — Read the three facts.
import numpy as np

values = np.arange(12)
print(values.ndim)
print(values.shape)
print(values.size)


1
(12,)
12


## Example 2 — Rewrap twelve elements

### Predict

$3 \times 4 = 12$, so `reshape(3, 4)` is legal. The first row is $0,1,2,3$ because reshape fills the last axis first: it walks across a row before it starts the next row.

$$
\begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
8 & 9 & 10 & 11
\end{bmatrix}
$$

### Run


In [2]:
import numpy as np

# 3 * 4 equals the original size, so the reshape is legal.
grid = np.arange(12).reshape(3, 4)
print(grid)
print(grid.shape)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


## Example 3 — Let one length be deduced

### Predict

`reshape(2, -1)` on 12 elements asks for 2 rows. The missing length is $12/2 = 6$, so the shape is `(2, 6)`.

### Run


In [3]:
import numpy as np

# -1 means "infer this length from the size."
grid = np.arange(12).reshape(2, -1)
print(grid.shape)
print(grid)


(2, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Example 4 — Change the dtype on purpose

### Predict

`astype` builds a new array. Truncating toward zero, `3.9` becomes `3`, the same rule as Python's `int`. The original array is unchanged.

### Run


In [4]:
import numpy as np

values = np.array([1.2, 3.9, -2.1])
whole = values.astype(int)
print(whole)
# astype did not edit the original.
print(values)


[ 1  3 -2]
[ 1.2  3.9 -2.1]


## A pitfall

`reshape(3, 3)` on 12 elements asks for 9 slots. Twelve elements cannot fill nine slots, and they cannot fill a shape whose product is anything but 12.

### Run


In [5]:
# A pitfall.
import numpy as np

values = np.arange(12)
try:
    print(values.reshape(3, 3))
except ValueError as error:
    print(type(error).__name__)


ValueError


## Summary

`size` is the product of the shape. `reshape` only changes the wrapping, and the new product must equal the old size. `-1` infers one length. `astype` converts the dtype by building a new array; it does not edit the old one.
