# 03 Indexing and Slicing

| | |
|---|---|
| **Path** | NumPy |
| **Prerequisite** | 02 |

Indexes start at 0. A negative index counts from the end. For two axes, `grid[row, column]` selects one element. A slice `start:stop` includes `start` and excludes `stop`, exactly as a Python slice does.

$$
\texttt{grid[i:j, k]}
$$

means rows $i, i+1, \ldots, j-1$, and column $k$.


## Example 1 — One row, one column, one element

### Predict

The grid is

$$
\begin{bmatrix}
0 & 1 & 2 \\
3 & 4 & 5
\end{bmatrix}.
$$

Row 1 is `[3, 4, 5]`. Column 2 is `[2, 5]`. The element in row 1, column 2 is 5. The last element of the flat order, index `-1` of the last row, is also 5.

### Run


In [1]:
import numpy as np

grid = np.arange(6).reshape(2, 3)
# One index selects a row. A pair selects row, then column.
print(grid[1])
print(grid[:, 2])
print(grid[1, 2])
print(grid[-1, -1])


[3 4 5]
[2 5]
5
5


## Example 2 — A slice keeps a rectangle

### Predict

`grid[:, :2]` keeps every row and columns 0 and 1, so the stop column 2 is excluded.

$$
\begin{bmatrix}
0 & 1 \\
3 & 4
\end{bmatrix}
$$

### Run


In [2]:
import numpy as np

grid = np.arange(6).reshape(2, 3)
# The stop column is excluded, just as in a Python slice.
print(grid[:, :2])
print(grid[:, :2].shape)


[[0 1]
 [3 4]]
(2, 2)


## Example 3 — Assign through an index

### Predict

`grid[0, 0] = 9` replaces one element. The rest of the first row stays `1, 2`.

### Run


In [3]:
# Example 3 — Assign through an index.
import numpy as np

grid = np.arange(6).reshape(2, 3)
grid[0, 0] = 9
print(grid)


[[9 1 2]
 [3 4 5]]


## Example 4 — A slice assignment fills a whole block

### Predict

Columns 0 and 1 of every row become 0. Column 2 is outside the slice, so it stays `2` and `5`.

### Run


In [4]:
import numpy as np

grid = np.arange(6).reshape(2, 3)
# One assignment writes every selected element.
grid[:, :2] = 0
print(grid)


[[0 0 2]
 [0 0 5]]


## A pitfall

`grid[0][1]` happens to work, because `grid[0]` is the first row and `[1]` indexes that row. The comma form `grid[0, 1]` is the one to write. The chained form becomes a real bug when the first index is a slice or a mask: you may be indexing a copy, or indexing the wrong axis. This cell shows the comma form and the chain agreeing on a single row, so the habit can be compared while they still match.

### Run


In [5]:
import numpy as np

grid = np.arange(6).reshape(2, 3)
# Both read row 0, column 1. Prefer the comma.
print(grid[0][1])
print(grid[0, 1])


1
1


## Summary

`grid[row, column]` selects one element. A lone slice on an axis keeps all of that axis, and the stop is excluded. Assignment through an index or a slice writes into the selected block. Write the comma form, not a chain of brackets.
