# 05 Vectorized Arithmetic

| | |
|---|---|
| **Path** | NumPy |
| **Prerequisite** | 04 |

Arithmetic on two arrays of the same shape is element by element.

$$
(a + b)_i = a_i + b_i,
\qquad
(a \cdot b)_i = a_i b_i.
$$

The star `*` is this elementwise product. It is not the matrix product. The matrix product arrives in lesson 15 and is written `@`.

A scalar stretches to every element: $(a + 3)_i = a_i + 3$.


## Example 1 — Add a scalar, then add two arrays

### Predict

Adding 10 to `[1, 2, 3]` gives `[11, 12, 13]`. Adding `[10, 20, 30]` gives `[11, 22, 33]`.

### Run


In [1]:
# Example 1 — Add a scalar, then add two arrays.
import numpy as np

values = np.array([1, 2, 3])
print(values + 10)
print(values + np.array([10, 20, 30]))


[11 12 13]
[11 22 33]


## Example 2 — The same squares, loop and array

### Predict

The squares of $1,2,3,4$ are $1,4,9,16$. The loop and `values ** 2` build the same numbers. The array expression is one line because the power applies to every element.

### Run


In [2]:
# Example 2 — The same squares, loop and array.
import numpy as np

values = np.array([1, 2, 3, 4])
loop = []
for number in values:
    loop.append(int(number ** 2))
print(loop)
print(values ** 2)


[1, 4, 9, 16]
[ 1  4  9 16]


## Example 3 — Elementwise product is not a dot product

### Predict

`[1, 2, 3] * [4, 5, 6]` is `[4, 10, 18]`. The dot product is the sum of those three products:

$$
1\cdot 4 + 2\cdot 5 + 3\cdot 6 = 4 + 10 + 18 = 32.
$$

`*` stops before the sum. `np.dot` does the sum. Lesson 14 treats the dot product as geometry; here it only distinguishes the two operations.

### Run


In [3]:
import numpy as np

left = np.array([1, 2, 3])
right = np.array([4, 5, 6])
# Star multiplies pairs and does not add them.
print(left * right)
print(np.dot(left, right))


[ 4 10 18]
32


## Example 4 — A comparison is arithmetic too

### Predict

`values >= 2` is a mask. Summing a mask counts the `True` entries, because `True` is 1. Two of the three values pass.

### Run


In [4]:
import numpy as np

values = np.array([1, 2, 3])
mask = values >= 2
print(mask)
# True counts as 1, so the sum is the number of passes.
print(mask.sum())


[False  True  True]
2


## A pitfall

Shapes that do not match, and that cannot broadcast, are an error. Broadcasting is the next lesson. Until the shapes agree, do not expect NumPy to line the arrays up from the left.

`[1, 2, 3] + [10, 20]` has lengths 3 and 2. Neither can pair with the other.

### Run


In [5]:
# A pitfall.
import numpy as np

try:
    print(np.array([1, 2, 3]) + np.array([10, 20]))
except ValueError as error:
    print(type(error).__name__)


ValueError


## Summary

Same-shape arithmetic works element by element, and a scalar reaches every element. `*` multiplies pairs. The dot product multiplies pairs and then adds. A mask sums to a count. Arrays whose lengths disagree are not added by lining them up from the left.
