# 08 Universal Functions

| | |
|---|---|
| **Path** | NumPy |
| **Prerequisite** | 07 |

A universal function, a ufunc, applies one scalar function to every element and accepts broadcasting. `np.sqrt`, `np.exp`, `np.log`, and `np.sin` are ufuncs. `math.sqrt` is not: it accepts one Python number.

`np.where(condition, yes, no)` chooses element by element. `np.clip` limits each element to an interval. `np.maximum` compares two arrays element by element, while `np.max` reduces one array to its largest value.


## Example 1 — A formula on every element

### Predict

Square roots of $1, 4, 9$ are $1, 2, 3$. The exponential of $0$ is $1$. Sine of $0$ is $0$, and sine of $\pi$ is $0$ in exact arithmetic. The stored floating-point value is only nearly zero, so the check uses a tolerance.

$$
\sqrt{1}=1,\quad \sqrt{4}=2,\quad \sqrt{9}=3,
\qquad
e^{0}=1,
\qquad
\sin \pi = 0.
$$

### Run


In [1]:
import numpy as np

print(np.sqrt(np.array([1.0, 4.0, 9.0])))
print(np.exp(0.0))
# sin(pi) is a tiny residual, not a printed 0, in binary floating point.
print(np.allclose(np.sin(np.pi), 0.0))


[1. 2. 3.]
1.0
True


## Example 2 — where chooses between two arrays

### Predict

Where the value is negative, replace it with 0. Elsewhere keep it. `[-2, 5, -1, 3]` becomes `[0, 5, 0, 3]`.

### Run


In [2]:
import numpy as np

values = np.array([-2, 5, -1, 3])
# The condition picks from the second array or the third, per element.
print(np.where(values < 0, 0, values))


[0 5 0 3]


## Example 3 — clip is an interval, maximum is a comparison

### Predict

Clipping `[-2, 0.5, 3]` to $[0, 1]$ gives `[0, 0.5, 1]`. `np.maximum` of `[1, 5, 2]` and `[4, 0, 2]` keeps the larger of each pair: `[4, 5, 2]`. `np.max` of the first array is the single number 5.

### Run


In [3]:
# Example 3 — clip is an interval, maximum is a comparison.
import numpy as np

print(np.clip(np.array([-2.0, 0.5, 3.0]), 0, 1))
print(np.maximum(np.array([1, 5, 2]), np.array([4, 0, 2])))
print(np.max(np.array([1, 5, 2])))


[0.  0.5 1. ]
[4 5 2]
5


## Example 4 — math.sqrt cannot see an array

### Predict

`math.sqrt` wants one number. Passing an array raises `TypeError`. `np.sqrt` is the array version of the same function.

### Run


In [4]:
# Example 4 — math.sqrt cannot see an array.
import math
import numpy as np

try:
    print(math.sqrt(np.array([1.0, 4.0, 9.0])))
except TypeError as error:
    print(type(error).__name__)
print(np.sqrt(np.array([1.0, 4.0, 9.0])))


TypeError
[1. 2. 3.]


## A pitfall

`np.log` of a negative number or of zero does not raise. It writes `nan` or `-inf` and lets you continue. A silent `nan` later poisons a sum. Check the inputs when a logarithm is part of the model.

$$
\log 1 = 0.
$$

### Run


In [5]:
import numpy as np
import warnings

# log of a nonpositive number warns and returns a special float.
warnings.filterwarnings("ignore", category=RuntimeWarning)
print(np.log(1.0))
print(np.isnan(np.log(-1.0)))
print(np.isneginf(np.log(0.0)))


0.0
True
True


## Summary

Ufuncs apply a scalar function to every element. Use `np.sqrt` and `np.log`, not `math.sqrt`, on an array. `np.where` picks between two results, `np.clip` enforces an interval, and `np.maximum` compares two arrays while `np.max` reduces one. A logarithm of a nonpositive number becomes `nan` or `-inf` instead of an exception.
