# 10 Sorting and Uniqueness

| | |
|---|---|
| **Path** | NumPy |
| **Prerequisite** | 09 |

`np.sort` returns a sorted copy. `array.sort()` sorts the array in place and returns `None`, the same contract as `list.sort`.

`argsort` returns the positions that would put the values in order. Those positions can reorder a second array in the same way.

`unique` returns the sorted distinct values. `return_counts=True` also returns how many times each distinct value appeared.


## Example 1 — A copy, then an in-place sort

### Predict

`np.sort` of `[3, 1, 2]` is `[1, 2, 3]`, and the original name still labels `[3, 1, 2]`. Calling `sort` on the array returns `None` and leaves the array sorted.

### Run


In [1]:
import numpy as np

values = np.array([3, 1, 2])
print(np.sort(values))
# The function built a copy. values is not sorted yet.
print(values)
returned = values.sort()
print(returned)
print(values)


[1 2 3]
[3 1 2]
None
[1 2 3]


## Example 2 — Positions, then the same order on a second array

### Predict

In `[3, 1, 2]` the smallest item is at index 1, then index 2, then index 0. So `argsort` is `[1, 2, 0]`.

Names `["c", "a", "b"]` taken in that same index order are `a`, `b`, `c`. The names follow the scores.

### Run


In [2]:
# Example 2 — Positions, then the same order on a second array.
import numpy as np

scores = np.array([3, 1, 2])
names = np.array(["c", "a", "b"])
order = np.argsort(scores)
print(order)
print(names[order])
print(scores[order])


[1 2 0]
['a' 'b' 'c']
[1 2 3]


## Example 3 — Distinct values and their counts

### Predict

`[1, 2, 2, 1, 3]` contains 1 twice, 2 twice, and 3 once. `unique` sorts the distinct values, so the pairs come out as 1, 2, 3 with counts 2, 2, 1.

### Run


In [3]:
# Example 3 — Distinct values and their counts.
import numpy as np

values = np.array([1, 2, 2, 1, 3])
distinct, counts = np.unique(values, return_counts=True)
print(distinct)
print(counts)


[1 2 3]
[2 2 1]


## Example 4 — The two largest, without sorting the whole story by hand

### Predict

`argsort` puts the smallest first. The last two positions of that order are the two largest scores. For `[10, 40, 25, 40]` the largest values are both 40. Stable details of ties belong to the implementation; the set of the two largest values is $\{40, 40\}$.

### Run


In [4]:
import numpy as np

scores = np.array([10, 40, 25, 40])
order = np.argsort(scores)
# The end of an ascending order holds the largest values.
print(scores[order[-2:]])


[40 40]


## A pitfall

`unique` sorts. It does not remember the first-seen order. If the first-seen order matters, record it yourself, as in the sets lesson of the Python path. This cell shows the sorted result beside a first-seen walk.

### Run


In [5]:
# A pitfall.
import numpy as np

values = np.array([3, 1, 3, 2])
print(np.unique(values))
seen = []
for item in values:
    if item not in seen:
        seen.append(int(item))
print(seen)


[1 2 3]
[3, 1, 2]


## Summary

`np.sort` returns a copy. `array.sort()` sorts in place and returns `None`. `argsort` gives positions you can use to reorder any companion array. `unique` returns sorted distinct values, and `return_counts=True` counts them. First-seen order is a different question, and `unique` does not answer it.
