# 11 Stacking and Splitting

| | |
|---|---|
| **Path** | NumPy |
| **Prerequisite** | 10 |

`concatenate` joins arrays along an axis that already exists. `stack` inserts a new axis and joins along that. `vstack` and `hstack` are the row and column habits for the cases you meet most often. `split` cuts one array into equal pieces.


## Example 1 — Two vectors become a matrix

### Predict

`vstack` of `[1, 2]` and `[3, 4]` makes two rows:

$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}.
$$

`hstack` joins them into one vector `[1, 2, 3, 4]`. `column_stack` uses each vector as a column:

$$
\begin{bmatrix} 1 & 3 \\ 2 & 4 \end{bmatrix}.
$$

### Run


In [1]:
# Example 1 — Two vectors become a matrix.
import numpy as np

left = np.array([1, 2])
right = np.array([3, 4])
print(np.vstack([left, right]))
print(np.hstack([left, right]))
print(np.column_stack([left, right]))


[[1 2]
 [3 4]]
[1 2 3 4]
[[1 3]
 [2 4]]


## Example 2 — concatenate needs a matching shape

### Predict

Two matrices of shape `(2, 2)`, stacked along axis 0, make shape `(4, 2)`. Along axis 1 they make shape `(2, 4)`.

### Run


In [2]:
# Example 2 — concatenate needs a matching shape.
import numpy as np

top = np.arange(4).reshape(2, 2)
bottom = np.arange(4, 8).reshape(2, 2)
print(np.concatenate([top, bottom], axis=0).shape)
print(np.concatenate([top, bottom], axis=1).shape)


(4, 2)
(2, 4)


## Example 3 — stack adds an axis

### Predict

`stack` inserts an axis. Two vectors of shape `(3,)` stacked on axis 0 produce shape `(2, 3)`.

`concatenate` does not insert an axis. On axis 0 it joins the two vectors end to end, and the shape is `(6,)`.

### Run


In [3]:
# Example 3 — stack adds an axis.
import numpy as np

first = np.array([1, 2, 3])
second = np.array([4, 5, 6])
print(np.stack([first, second], axis=0).shape)
print(np.concatenate([first, second], axis=0).shape)


(2, 3)
(6,)


## Example 4 — Split into equal pieces

### Predict

`arange(6)` cut into 3 pieces is `[0, 1]`, `[2, 3]`, and `[4, 5]`.

### Run


In [4]:
# Example 4 — Split into equal pieces.
import numpy as np

parts = np.split(np.arange(6), 3)
for part in parts:
    print(part)


[0 1]
[2 3]
[4 5]


## A pitfall

Rows of different lengths cannot be stacked. A shape `(2,)` and a shape `(3,)` do not share the column count, so `vstack` raises. Reshape or pad before you stack; do not expect NumPy to fill the gap.

### Run


In [5]:
# A pitfall.
import numpy as np

try:
    print(np.vstack([np.array([1, 2]), np.array([3, 4, 5])]))
except ValueError as error:
    print(type(error).__name__)


ValueError


## Summary

`vstack` adds rows, `hstack` joins end to end, and `column_stack` turns vectors into columns. `concatenate` joins an axis that already exists. `stack` creates a new axis. `split` cuts an axis into equal pieces. Arrays in a stack must agree on every axis that is not the one you are joining.
